// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconsIconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconsIconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconsIconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconsIconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconsIconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    Test: typeof import('./src/components/Test.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}

export { }
